# Generated by Django 5.1.6 on 2025-09-02 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='deals/')),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deal_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('link', models.URLField(blank=True, help_text='Enter the affiliate link (e.g., Amazon Associates URL with tracking ID).', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
